{{-- resources/views/admin/exports/users-docx.blade.php --}}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Users Export - {{ date('Y-m-d') }}</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            font-size: 11pt;
            line-height: 1.3;
        }
        h1 {
            color: #28a745;
            font-size: 18pt;
            text-align: center;
            margin-bottom: 20px;
        }
        .header-info {
            margin-bottom: 20px;
            padding: 10px;
            background: #f0f0f0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th {
            background: #28a745;
            color: white;
            padding: 8px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 6px;
            border-bottom: 1px solid #ddd;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
            color: #666;
            font-size: 9pt;
        }
    </style>
</head>
<body>
    <h1>USERS EXPORT REPORT</h1>

    <div class="header-info">
        <p><strong>Generated:</strong> {{ date('F j, Y \a\t g:i A') }}</p>
        <p><strong>Total Users:</strong> {{ $users->count() }}</p>
        @if(request('search'))
        <p><strong>Search Filter:</strong> "{{ request('search') }}"</p>
        @endif
        @if(request('role'))
        <p><strong>Role Filter:</strong> {{ ucfirst(request('role')) }}</p>
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Status</th>
                <th>Identifications</th>
                <th>Verified</th>
                <th>Joined</th>
            </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
            <tr>
                <td>{{ $user->id }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ ucfirst($user->role) }}</td>
                <td>{{ isset($user->is_active) ? ($user->is_active ? 'Active' : 'Inactive') : 'Active' }}</td>
                <td>{{ $user->identifications_count ?? 0 }}</td>
                <td>{{ $user->email_verified_at ? 'Yes' : 'No' }}</td>
                <td>{{ $user->created_at->format('Y-m-d') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by {{ config('app.name') }} | {{ date('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>
